services:
  app:
    image: socrates1024/self-attesting-tee@sha256:1724257998a2bcbff3508b923cf1667e02459a859fa1edf32f17e47171cf0b20
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
