services:
  app:
    image: socrates1024/self-attesting-tee@sha256:5d6888da0aeb748802a2f284c757de5f5bbef5e4fca3340c4cd17079f8101a8e
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
